import polars as pl


pl.Config.set_tbl_rows(120)
pl.Config.set_fmt_str_lengths(160)


# ---------------------------------------------------------
# Load Script 32 output.
# ---------------------------------------------------------

df = pl.read_parquet(
    "data/fg_made_kickoff_audit.parquet"
)


print(
    f"Loaded {df.height:,} made-FG rows."
)


# ---------------------------------------------------------
# The key correction:
#
# A kickoff is causally generated by this made FG only if
# that kickoff occurs BEFORE the next offensive state.
#
# If an offensive state occurs first, then the made-kick
# row was followed by some continuation / penalty / replay
# situation rather than an ordinary kickoff.
# ---------------------------------------------------------

df = df.with_columns(

    pl.when(
        pl.col("state_play_id").is_null()
    )
    .then(
        pl.lit("no_later_state")
    )

    .when(
        pl.col("crossed_halftime")
    )
    .then(
        pl.lit("crossed_halftime")
    )

    .when(
        pl.col("entered_overtime")
    )
    .then(
        pl.lit("entered_overtime")
    )

    .when(
        pl.col("kickoff_play_id").is_not_null()
        &
        pl.col("state_play_id").is_not_null()
        &
        (
            pl.col("kickoff_play_id")
            <
            pl.col("state_play_id")
        )
    )
    .then(
        pl.lit("kickoff_before_state")
    )

    .when(
        pl.col("kickoff_play_id").is_not_null()
        &
        pl.col("state_play_id").is_not_null()
        &
        (
            pl.col("state_play_id")
            <
            pl.col("kickoff_play_id")
        )
    )
    .then(
        pl.lit("state_before_kickoff")
    )

    .when(
        pl.col("kickoff_play_id").is_null()
    )
    .then(
        pl.lit("no_kickoff_found")
    )

    .otherwise(
        pl.lit("other")
    )

    .alias("causal_path")

)


# ---------------------------------------------------------
# Description diagnostics for the suspicious
# state-before-kickoff rows.
# ---------------------------------------------------------

df = df.with_columns([

    pl.col("desc")
    .fill_null("")
    .str.contains(
        "(?i)penalty"
    )
    .alias("fg_desc_has_penalty"),

    pl.col("desc")
    .fill_null("")
    .str.contains(
        "(?i)no play|nullified"
    )
    .alias("fg_desc_no_play"),

])


print(
    "\nCAUSAL PATH BY ERA"
)

print(
    df
    .group_by([
        "era",
        "causal_path",
    ])
    .len()
    .sort([
        "era",
        "causal_path",
    ])
)


# ---------------------------------------------------------
# Audit the rows where offense resumes BEFORE any kickoff.
# ---------------------------------------------------------

continued = df.filter(
    pl.col("causal_path")
    == "state_before_kickoff"
)


print(
    "\nSTATE-BEFORE-KICKOFF SUMMARY"
)

print(
    continued.select([

        pl.len()
        .alias("plays"),

        pl.col(
            "fg_desc_has_penalty"
        )
        .sum()
        .alias("penalty_desc"),

        pl.col(
            "fg_desc_no_play"
        )
        .sum()
        .alias("no_play_desc"),

    ])
)


print(
    "\nSTATE-BEFORE-KICKOFF SCORE CHANGES"
)

print(
    continued
    .group_by(
        "score_change"
    )
    .len()
    .sort(
        "score_change"
    )
)


print(
    "\nSTATE-BEFORE-KICKOFF DETAILS"
)

print(
    continued
    .select([
        "season",
        "week",
        "game_id",
        "play_id",

        "qtr",
        "game_seconds_remaining",

        "posteam",
        "defteam",

        "score_differential",
        "score_change",

        "fg_desc_has_penalty",
        "fg_desc_no_play",

        "state_play_id",
        "state_game_seconds_remaining",
        "state_posteam",
        "state_down",
        "state_ydstogo",
        "state_yardline_100",

        "kickoff_play_id",
        "kickoff_qtr",
        "kickoff_game_seconds_remaining",

        "desc",
        "state_desc",
        "kickoff_desc",
    ])
    .sort([
        "season",
        "week",
    ])
)


# ---------------------------------------------------------
# Clean causal kickoff rows only.
# ---------------------------------------------------------

clean = df.filter(
    pl.col("causal_path")
    == "kickoff_before_state"
)


# ---------------------------------------------------------
# Corrected post-kickoff outcome class.
# ---------------------------------------------------------

clean = clean.with_columns(

    pl.when(
        (pl.col("score_change") == 3)
        &
        (
            pl.col("state_posteam")
            ==
            pl.col("defteam")
        )
    )
    .then(
        pl.lit(
            "receiver_ball_no_extra_score"
        )
    )

    .when(
        (pl.col("score_change") == 3)
        &
        (
            pl.col("state_posteam")
            ==
            pl.col("posteam")
        )
    )
    .then(
        pl.lit(
            "kicking_team_recovered_kickoff"
        )
    )

    .when(
        pl.col("score_change") < 3
    )
    .then(
        pl.lit(
            "opponent_scored_on_kickoff_sequence"
        )
    )

    .when(
        pl.col("score_change") > 3
    )
    .then(
        pl.lit(
            "kicking_team_extra_score"
        )
    )

    .otherwise(
        pl.lit("other")
    )

    .alias(
        "clean_transition_class"
    )

)


print(
    "\nCLEAN MADE-FG KICKOFF TRANSITIONS"
)

print(
    clean
    .group_by([
        "era",
        "clean_transition_class",
    ])
    .len()
    .sort([
        "era",
        "clean_transition_class",
    ])
)


# ---------------------------------------------------------
# Corrected onside rates.
# ---------------------------------------------------------

print(
    "\nCLEAN KICKOFF TYPE BY ERA"
)

print(
    clean
    .group_by("era")
    .agg([

        pl.len()
        .alias("kickoffs"),

        pl.col("onside_kick")
        .sum()
        .alias("onside_kicks"),

        pl.col("onside_kick")
        .mean()
        .alias("onside_rate"),

    ])
    .sort("era")
)


# ---------------------------------------------------------
# Kickoff recoveries by kicking team.
#
# Split onside vs non-onside because a muffed normal
# kickoff can also be recovered by the kicking team.
# ---------------------------------------------------------

recoveries = clean.filter(
    pl.col("clean_transition_class")
    ==
    "kicking_team_recovered_kickoff"
)


print(
    "\nKICKING-TEAM KICKOFF RECOVERIES"
)

print(
    recoveries
    .group_by([
        "era",
        "onside_kick",
    ])
    .len()
    .sort([
        "era",
        "onside_kick",
    ])
)


print(
    "\nKICKING-TEAM RECOVERY DETAILS"
)

print(
    recoveries
    .select([
        "season",
        "week",
        "game_id",
        "play_id",

        "qtr",
        "game_seconds_remaining",

        "onside_kick",

        "kickoff_play_id",
        "kickoff_desc",

        "state_play_id",
        "state_posteam",
        "state_down",
        "state_ydstogo",
        "state_yardline_100",

        "score_change",
    ])
    .sort([
        "season",
        "week",
    ])
)


# ---------------------------------------------------------
# Ordinary post-kickoff receiving states.
# ---------------------------------------------------------

ordinary = clean.filter(
    pl.col("clean_transition_class")
    ==
    "receiver_ball_no_extra_score"
)


ordinary_aggs = [

    pl.len()
    .alias("plays"),

    pl.col("state_yardline_100")
    .mean()
    .alias("mean_yardline"),

    pl.col("state_yardline_100")
    .median()
    .alias("median_yardline"),

    (
        pl.col("state_yardline_100")
        == 80
    )
    .mean()
    .alias("own_20_rate"),

    (
        pl.col("state_yardline_100")
        == 75
    )
    .mean()
    .alias("own_25_rate"),

    (
        pl.col("state_yardline_100")
        == 70
    )
    .mean()
    .alias("own_30_rate"),

    pl.col("seconds_to_state")
    .mean()
    .alias("mean_seconds"),

    pl.col("seconds_to_state")
    .median()
    .alias("median_seconds"),

]


# If nflverse included kickoff touchback,
# add it to the summary.
if "kickoff_touchback" in ordinary.columns:

    ordinary_aggs.append(

        pl.col("kickoff_touchback")
        .fill_null(0)
        .mean()
        .alias("touchback_rate")

    )


print(
    "\nCLEAN ORDINARY RECEIVING STATE BY ERA"
)

print(
    ordinary
    .group_by("era")
    .agg(
        ordinary_aggs
    )
    .sort("era")
)


# ---------------------------------------------------------
# Kickoff scoring branches.
# ---------------------------------------------------------

print(
    "\nCLEAN KICKOFF SCORING EVENTS"
)

print(
    clean
    .filter(
        pl.col("clean_transition_class")
        .is_in([
            "opponent_scored_on_kickoff_sequence",
            "kicking_team_extra_score",
        ])
    )
    .group_by([
        "era",
        "clean_transition_class",
        "score_change",
    ])
    .len()
    .sort([
        "era",
        "clean_transition_class",
        "score_change",
    ])
)


# ---------------------------------------------------------
# Print those rare scoring events for manual inspection.
# ---------------------------------------------------------

print(
    "\nCLEAN KICKOFF SCORING DETAILS"
)

print(
    clean
    .filter(
        pl.col("clean_transition_class")
        .is_in([
            "opponent_scored_on_kickoff_sequence",
            "kicking_team_extra_score",
        ])
    )
    .select([
        "season",
        "week",
        "game_id",
        "play_id",

        "score_change",

        "onside_kick",

        "kickoff_play_id",
        "kickoff_desc",

        "state_play_id",
        "state_posteam",
        "state_yardline_100",

        "desc",
        "state_desc",
    ])
    .sort([
        "season",
        "week",
    ])
)


# ---------------------------------------------------------
# Period-end cases remain separate from the kickoff model.
# ---------------------------------------------------------

print(
    "\nPERIOD-END / TERMINAL MADE FGS"
)

print(
    df
    .filter(
        pl.col("causal_path")
        .is_in([
            "crossed_halftime",
            "entered_overtime",
            "no_later_state",
        ])
    )
    .group_by([
        "era",
        "causal_path",
    ])
    .len()
    .sort([
        "era",
        "causal_path",
    ])
)


# ---------------------------------------------------------
# Save corrected audit.
# ---------------------------------------------------------

df.write_parquet(
    "data/fg_made_causal_kickoff_audit.parquet"
)


print(
    "\nSaved:"
)

print(
    "data/fg_made_causal_kickoff_audit.parquet"
)